layout_spectrum: 0.4229391
typography_spectrum: 0.5430108
color:
  saturation: 0.7640999
  lightness: 0.7164274
  brandStrength: 0.2651854
  rhythmicContrast: 0.2773807
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
name: Cityboybushcraft
